// <auto-generated />
using AnimalShelterApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalShelterApi.Migrations
{
    [DbContext(typeof(AnimalShelterApiContext))]
    [Migration("20200821224614_secondary")]
    partial class secondary
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnimalShelterApi.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AdoptionFee");

                    b.Property<string>("AnimalDescription");

                    b.Property<string>("AnimalHealth");

                    b.Property<string>("AnimalName");

                    b.Property<string>("SuggestedHome");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            AdoptionFee = 0,
                            AnimalDescription = "Chonky Boi",
                            AnimalHealth = "Healthy, all shots take care of, neutered!",
                            AnimalName = "Toby",
                            SuggestedHome = "Toby is great with kids and an active environment, is also able to relax comfortably by himself or with cats, is afraid of other dogs."
                        },
                        new
                        {
                            AnimalId = 2,
                            AdoptionFee = 50,
                            AnimalDescription = "Discount Garfield",
                            AnimalHealth = "Healthy, all shots take care of, neutered!",
                            AnimalName = "Gabe",
                            SuggestedHome = "Gabe mostly just sleeps, anywhere quiet without young children or dogs is preferred."
                        },
                        new
                        {
                            AnimalId = 3,
                            AdoptionFee = 250,
                            AnimalDescription = "Camera Blur",
                            AnimalHealth = "Healthy, all shots take care of, neutered!",
                            AnimalName = "Yeet",
                            SuggestedHome = "Yeet is great with anyone who's high energy, terrorizes children."
                        },
                        new
                        {
                            AnimalId = 4,
                            AdoptionFee = 1000,
                            AnimalDescription = "Very friendly when asleep in the other room",
                            AnimalHealth = "Afraid to check",
                            AnimalName = "Xander",
                            SuggestedHome = "Xander is the best. Really. He doesn't bite at all. I was born with 9 fingers."
                        },
                        new
                        {
                            AnimalId = 5,
                            AdoptionFee = 250000000,
                            AnimalDescription = "I can't remember",
                            AnimalHealth = "Unknown",
                            AnimalName = "He-Who-Sleeps",
                            SuggestedHome = "Somewhere with alot of room and sacrifi- an influx of new faces daily."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
