// <auto-generated />
using AnimalShelterApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalShelterApi.Migrations
{
    [DbContext(typeof(AnimalShelterApiContext))]
    partial class AnimalShelterApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnimalShelterApi.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AdoptionFee");

                    b.Property<string>("AnimalDescription");

                    b.Property<string>("AnimalHealth");

                    b.Property<string>("AnimalName");

                    b.Property<string>("SuggestedHome");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            AdoptionFee = 0,
                            AnimalDescription = "Chonky Boi",
                            AnimalHealth = "Healthy, all shots take care of, neutered!",
                            AnimalName = "Toby",
                            SuggestedHome = "Toby is great with kids and an active environment, is also able to relax comfortably by himself or with cats, is afraid of other dogs."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
